CREATE ROLE flood_api;
CREATE ROLE flood_operator;
CREATE ROLE flood_injector;
CREATE ROLE flood_observer;
GO
GRANT SELECT ON flood.database_identity TO flood_api;
GRANT SELECT ON flood.runs TO flood_api;
GRANT SELECT ON flood.run_grants TO flood_api;
GRANT SELECT ON flood.shelters TO flood_api;
GRANT SELECT, INSERT, UPDATE ON flood.requests TO flood_api;
GRANT SELECT, INSERT, UPDATE ON flood.allocations TO flood_api;
GRANT SELECT, INSERT ON flood.events TO flood_api;
GRANT SELECT, INSERT ON flood.receipts TO flood_api;
GRANT SELECT ON flood.database_identity TO flood_operator;
GRANT VIEW DEFINITION TO flood_operator;
GRANT SELECT, INSERT, UPDATE ON flood.runs TO flood_operator;
GRANT SELECT, INSERT, UPDATE ON flood.run_grants TO flood_operator;
GRANT SELECT, INSERT, UPDATE ON flood.sql_run_grants TO flood_operator;
GRANT SELECT, INSERT, UPDATE ON flood.shelters TO flood_operator;
GRANT SELECT, INSERT, UPDATE ON flood.requests TO flood_operator;
GRANT SELECT, INSERT, UPDATE ON flood.allocations TO flood_operator;
GRANT SELECT, INSERT ON flood.events TO flood_operator;
GRANT SELECT, INSERT ON flood.receipts TO flood_operator;
GRANT SELECT, INSERT ON flood.recovery_evidence TO flood_operator;
GRANT EXECUTE ON flood.ReadOccupancy TO flood_observer;
GRANT EXECUTE ON flood.ReadOccupancy TO flood_injector;
GRANT EXECUTE ON flood.ReadOccupancy TO flood_operator;
GRANT EXECUTE ON flood.UpdateOccupancy TO flood_injector;
GRANT EXECUTE ON flood.UpdateOccupancy TO flood_operator;
