"""Initial authoring schema."""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=True),
        sa.Column("actor", sa.Unicode(length=256), nullable=False),
        sa.Column("operation", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_organization_id"), "audit", ["organization_id"], unique=False)
    op.create_index(op.f("ix_audit_workspace_id"), "audit", ["workspace_id"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.Unicode(length=160), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "administrators",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("object_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "object_id"),
    )
    op.create_table(
        "environments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.Unicode(length=160), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_environments_organization_id"), "environments", ["organization_id"], unique=False
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.Unicode(length=160), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workspaces_organization_id"), "workspaces", ["organization_id"], unique=False
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("previous_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.Unicode(length=160), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("blob_key", sa.String(length=200), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("actor", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["previous_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blob_key"),
    )
    op.create_index(op.f("ix_assets_workspace_id"), "assets", ["workspace_id"], unique=False)
    op.create_table(
        "connections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=True),
        sa.Column("environment_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.Unicode(length=160), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Unicode(length=2000), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connections_organization_id"), "connections", ["organization_id"], unique=False
    )
    op.create_table(
        "memberships",
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("object_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("workspace_id", "object_id"),
    )
    op.create_table(
        "scenarios",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("content", sa.UnicodeText(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scenarios_workspace_id"), "scenarios", ["workspace_id"], unique=False)
    op.create_table(
        "comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scenario_id", sa.String(length=36), nullable=False),
        sa.Column("base_version", sa.Integer(), nullable=False),
        sa.Column("body", sa.UnicodeText(), nullable=False),
        sa.Column("actor", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comments_scenario_id"), "comments", ["scenario_id"], unique=False)
    op.create_table(
        "connection_grants",
        sa.Column("connection_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("connection_id", "workspace_id"),
    )
    op.create_table(
        "planning_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scenario_id", sa.String(length=36), nullable=False),
        sa.Column("actor", sa.String(length=36), nullable=False),
        sa.Column("base_version", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.UnicodeText(), nullable=False),
        sa.Column("context", sa.UnicodeText(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("proposal", sa.UnicodeText(), nullable=True),
        sa.Column("error", sa.Unicode(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_planning_requests_scenario_id"), "planning_requests", ["scenario_id"], unique=False
    )
    op.create_table(
        "revisions",
        sa.Column("scenario_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.UnicodeText(), nullable=False),
        sa.Column("actor", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
        ),
        sa.PrimaryKeyConstraint("scenario_id", "version"),
    )
    op.create_table(
        "dispatch_intents",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt", sa.DateTime(), nullable=False),
        sa.Column("lease_until", sa.DateTime(), nullable=True),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("last_error", sa.Unicode(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["planning_requests.id"],
        ),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_index(
        op.f("ix_dispatch_intents_next_attempt"), "dispatch_intents", ["next_attempt"], unique=False
    )
    op.create_index(op.f("ix_dispatch_intents_state"), "dispatch_intents", ["state"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dispatch_intents_state"), table_name="dispatch_intents")
    op.drop_index(op.f("ix_dispatch_intents_next_attempt"), table_name="dispatch_intents")
    op.drop_table("dispatch_intents")
    op.drop_table("revisions")
    op.drop_index(op.f("ix_planning_requests_scenario_id"), table_name="planning_requests")
    op.drop_table("planning_requests")
    op.drop_table("connection_grants")
    op.drop_index(op.f("ix_comments_scenario_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_scenarios_workspace_id"), table_name="scenarios")
    op.drop_table("scenarios")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_connections_organization_id"), table_name="connections")
    op.drop_table("connections")
    op.drop_index(op.f("ix_assets_workspace_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_workspaces_organization_id"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_environments_organization_id"), table_name="environments")
    op.drop_table("environments")
    op.drop_table("administrators")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_audit_workspace_id"), table_name="audit")
    op.drop_index(op.f("ix_audit_organization_id"), table_name="audit")
    op.drop_table("audit")
    # ### end Alembic commands ###
